name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install JDK
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      # Build Debug version
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      
      # Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk
